### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by ghost** [bry-an/simple-weather#1]
| |
| - |
| ![wireframe](https://user-images.githubusercontent.com/64174978/101866236-8a07bb00-3b35-11eb-84f8-3796f7214eac.png) |

**Comment by ghost** [comment]
```
--Card
  --CardHeader
    --CurrentWeather
    --Chart
    --Hour
  --CardFooter
    --Day
```

**Comment by ghost** [comment]
@bry-an What do you think about the component structure?

**Comment by bry-an** [comment]
I like it!

**Comment by ghost** [comment]
Basic wireframe is done.
I will fix the css that's all over the place.
