### ISSUE TITLE
12 AM shouldn't be displayed in a selected day

### ISSUE THREAD

**Issue by ghost** [bry-an/simple-weather#19]
| Current Day | Other Day |
| --- | --- |
![image](https://user-images.githubusercontent.com/64174978/104412814-4cc68c80-552a-11eb-97b9-1dba764e7d0c.png) | ![image](https://user-images.githubusercontent.com/64174978/104412817-5223d700-552a-11eb-82ef-a17d17bda495.png)
| Should say **11 PM** in the top left corner | Shouldn't display any time at all in the top left corner |

**Comment by ghost** [comment]
@bry-an How can we determine if it's the first day that's selected (to display the time)?

**Comment by ghost** [comment]
| Current Day | Other Day |
| --- | --- |
![image](https://user-images.githubusercontent.com/64174978/104413256-41279580-552b-11eb-8190-e6b2c1afbeed.png) | ![image](https://user-images.githubusercontent.com/64174978/104413270-484ea380-552b-11eb-8b61-cd43312254bb.png)

**Comment by bry-an** [comment]
> @bry-an How can we determine if it's the first day that's selected (to display the time)?

@mi544 We could create a Vuex getter that returns whether the first day is selected.

**Comment by ghost** [comment]
@bry-an That sounds like a solid plan. We should implement it!

**Comment by ghost** [comment]
Implemented, then changed the API team so no longer relevant.
