### ISSUE TITLE
A click on a day should update the current weather data being displayed

### ISSUE THREAD

**Issue by ghost** [bry-an/simple-weather#2]
A click on a day `div` should update the current weather data being displayed in the `CardHeader`

**Comment by ghost** [comment]
@bry-an  I merged the branch into dev and resolved all the conflicts

**Comment by ghost** [comment]
Continuing to work on that branch. Merged dev into it to have the most up to date changes. Please let me know if that shouldn't be the case and the workflow with git should be different.

Made the first day in the card always selected by default just like on ddg.gg

**Comment by ghost** [comment]
Working on displaying current data in the `CardHeader->CurrentWeather` now.
It may require a slightly different approach with APIs If we want to make it accurate to the hour. It's only accurate to the day right now

**Comment by ghost** [comment]
Basic weather information about every day can now be viewed by clicking on it.


https://user-images.githubusercontent.com/64174978/103140391-55ead900-46a3-11eb-9718-032809674dcf.mp4

**Comment by ghost** [comment]
Now shows day of the week, time, and weather conditions description

**Comment by bry-an** [comment]
Work is complete.
